In [2]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [3]:
import numpy as np
a = np.zeros(7) #массив из 7 нулей
print(a)

[0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
a = np.ones(8) # массив из 8 нулей
print(a)

In [5]:
import numpy as np
a = np.arange(0, 21, 3) #массив от 0 до 21 с шагом 3
print(a)

[ 0  3  6  9 12 15 18]


In [7]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a.shape) #показывает форму массива
print(a.dtype) #показывает тип элементов массива

(4,)
int64


In [11]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7])
print(a[5])  #выводит элемент массива под номером 5 (индексация идет с 0)
print(a[3:7]) # срез массива от 4 до 7 включительно

6
[4 5 6 7]


In [12]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7])
print(a + 1) #к каждому элементу массива прибавляется 1
print(a * 3) # каждый элемент массива умножается на 3
print(np.mean(a)) # среднее значение массива
print(np.min(a)) #минимальное значиение в массиве
print(np.max(a)) #максимальное значение в массиве

[2 3 4 5 6 7 8]
[ 3  6  9 12 15 18 21]
4.0
1
7
